# Generated by Django 2.1.4 on 2019-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_destination_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='action',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=50),
        ),
    ]
