# Generated by Django 2.1.4 on 2019-01-29 17:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_destination_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.FileField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
