# Generated by Django 2.1.4 on 2019-01-30 10:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190130_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekkingtype',
            name='trekking_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cycling', 'Cycling'), ('Walking', 'Walking'), ('Biking', 'Biking'), ('Peak Climbing', 'Peak Climbing'), ('Others', 'Others')], max_length=50),
        ),
    ]
