# Generated by Django 2.1.4 on 2019-01-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190130_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trekkingtype',
            old_name='destination',
            new_name='Destination',
        ),
    ]
