# Generated by Django 2.1.4 on 2019-01-30 11:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190130_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationtype',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='destinationtype',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trekkingtype',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='published_date',
        ),
        migrations.AddField(
            model_name='destination',
            name='accomodation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hotel', 'Hotel'), ('Teahouse', 'Teahouse'), ('Motel', 'Motel'), ('Himalayas', 'Himalayas'), ('Tent', 'Tent'), ('Homestay', 'Homestay')], default='Hotel', max_length=44),
        ),
        migrations.AddField(
            model_name='destination',
            name='destinaton_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Pilgrims', 'Pilgrims'), ('Waterbody', 'Waterbody'), ('Himalayas', 'Himalayas'), ('Nature Seeing', 'Nature Seeing'), ('Others', 'Others')], default='Adventure', max_length=59),
        ),
        migrations.AddField(
            model_name='destination',
            name='trekking_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cycling', 'Cycling'), ('Walking', 'Walking'), ('Biking', 'Biking'), ('Peak Climbing', 'Peak Climbing'), ('Others', 'Others')], default='Walking', max_length=43),
        ),
        migrations.DeleteModel(
            name='AccomodationType',
        ),
        migrations.DeleteModel(
            name='DestinationType',
        ),
        migrations.DeleteModel(
            name='TrekkingType',
        ),
    ]
