# Generated by Django 2.1.4 on 2019-01-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190130_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default='1'),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default='1'),
        ),
    ]
