# Generated by Django 2.1.4 on 2019-02-02 07:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190131_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='accomodation_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hotel', 'Hotel'), ('Teahouse', 'Teahouse'), ('Motel', 'Motel'), ('Tent', 'Tent'), ('Homestay', 'Homestay')], default='Hotel', max_length=34),
        ),
    ]
